"""Security utilities: password hashing and JWT handling."""

from __future__ import annotations

from datetime import datetime, timedelta, timezone

import bcrypt
from jose import JWTError, jwt

from app.config import (
    ACCESS_TOKEN_EXPIRE_MINUTES,
    JWT_ALGORITHM,
    JWT_SECRET_KEY,
)

# ---------------------------------------------------------------------------
# Password hashing
#
# Note: we use the ``bcrypt`` library directly instead of passlib. passlib is
# notoriously incompatible with recent bcrypt releases (it rejects every hash
# generated by bcrypt>=4.1, which manifests exactly as "existing accounts can
# no longer sign in but new signups work"). bcrypt is also the dependency that
# is actually declared in requirements.txt.
# ---------------------------------------------------------------------------


def hash_password(password: str) -> str:
    """Hash a password using bcrypt with a random salt ($2b$ prefix)."""
    if password is None or len(password) == 0:
        raise ValueError("Password cannot be empty")
    hashed = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt())
    return hashed.decode("utf-8")


def verify_password(plain_password: str, hashed_password: str | None) -> bool:
    """Verify a plaintext password against a stored bcrypt hash.

    Returns False for malformed hashes (including hashes written by other
    tools, e.g. ``$2y$``) and for accounts without a password (e.g. users
    created via Google sign-in), so a stale record can never cause a 500
    during login.
    """
    if not hashed_password:
        return False
    try:
        return bcrypt.checkpw(
            plain_password.encode("utf-8"),
            hashed_password.encode("utf-8"),
        )
    except (ValueError, TypeError):
        return False


# ---------------------------------------------------------------------------
# JWT
# ---------------------------------------------------------------------------
def create_access_token(data: dict, expires_delta: timedelta | None = None) -> str:
    to_encode = data.copy()
    expire = datetime.now(timezone.utc) + (
        expires_delta or timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    )
    to_encode.update({"exp": expire})
    return jwt.encode(to_encode, JWT_SECRET_KEY, algorithm=JWT_ALGORITHM)


def decode_access_token(token: str) -> dict | None:
    try:
        return jwt.decode(token, JWT_SECRET_KEY, algorithms=[JWT_ALGORITHM])
    except JWTError:
        return None
