"""add google auth fields

Revision ID: 86fb2a4bd24a
Revises: 2ec44ff80786
Create Date: 2026-09-04 20:55:06.847922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86fb2a4bd24a'
down_revision: Union[str, None] = '2ec44ff80786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add Google OAuth fields to users.
    #
    # NOTE: this migration was originally autogenerated against a dev database
    # that still contained a leftover `playing_with_neon` table and an index
    # drift on chunks.search_vector, which produced two unwanted operations
    # (drop_table('playing_with_neon') and drop_index('ix_chunks_search_vector')).
    # Both have been removed: dropping the chunks GIN index silently degraded
    # keyword-search performance, and dropping a table that fresh environments
    # never had would crash `alembic upgrade head` from scratch.
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('picture_url', sa.String(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'picture_url')
    op.drop_column('users', 'name')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###